title: Amazfish
description: Companion application for your smartwatch
show_downloads: false
# google_analytics:
theme: jekyll-theme-slate

collections:
  devices:
    output: true
    permalink: /:collection/:name/index.html
    defaults:
      layout: "device"


defaults:
  -
    scope:
      path: ""
      type: "devices" # a collection in your site, in plural form
    values:
      layout: "device"
